//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WordGLXT.rc
//
#define IDD_SelectFilePath              3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORDGLXT_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DWDAN                       129
#define IDD_WDLB                        130
#define IDI_CHILDICON1                  131
#define IDI_CHILDICON3                  132
#define IDI_CHILDICON2                  133
#define IDI_ROOTICON                    134
#define IDR_MENU1                       135
#define IDD_YHGL                        137
#define IDD_KLXG                        138
#define IDD_DIALOGIN                    139
#define IDD_WDgldlg                     140
#define IDI_CHILDICON4                  141
#define IDI_ICONDANWEI                  142
#define IDI_ICONFIND                    143
#define IDI_ICONYHGL                    144
#define IDI_ICONMIMA                    145
#define IDI_ICONLOGIN                   146
#define IDI_ICONWDLB                    147
#define IDD_LookFileAttri               148
#define IDD_DataBase                    150
#define IDR_TOOLBAR1                    151
#define IDI_ICON1                       158
#define IDB_BITMAP1                     159
#define IDI_ICONDB                      160
#define IDI_ICONExit                    161
#define IDI_ICONModify                  162
#define IDI_ICONFileAttri               163
#define IDI_ICONUser                    164
#define IDI_ICONDel                     165
#define IDI_ICONAdd                     166
#define IDB_BITMAP_Login                180
#define IDB_BITMAP_QR                   181
#define IDB_BITMAP_QX                   182
#define IDB_BITMAP_Title                183
#define IDB_BITMAP_Close                184
#define IDI_ICONMod                     189
#define IDI_ICONSJKBF                   192
#define IDI_ICONSJKHF                   193
#define IDI_ICONDWDA                    194
#define IDI_ICONScan                    200
#define IDI_ICONLog                     204
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_MODBUTTON                   1005
#define IDC_EDIT7                       1005
#define IDC_EDIT6                       1006
#define IDC_DELBUTTON                   1007
#define IDC_TREE1                       1010
#define IDC_RICHEDIT1                   1011
#define IDC_COMBO1                      1012
#define IDC_BUTTON1                     1013
#define IDC_STATICyh                    1014
#define IDC_TAB1                        1015
#define IDC_RADIO1                      1016
#define IDC_RADIO2                      1017
#define IDC_WJLJXZ                      1018
#define IDC_STATIC1                     1019
#define IDC_STATIC2                     1020
#define IDC_STATIC3                     1021
#define IDC_STATIC4                     1022
#define IDC_STATIC5                     1023
#define IDC_STATIC6                     1024
#define IDC_STATIC7                     1025
#define IDC_STATIC8                     1026
#define IDC_LIST1                       1027
#define IDC_BUTTONDEL                   1028
#define IDC_BUTTON_DelWD                1028
#define ID_BNAddFile                    1030
#define IDC_Normal                      1033
#define IDC_ReadOnly                    1034
#define IDC_Hide                        1035
#define IDC_System                      1036
#define IDC_VolumeLabel                 1037
#define IDC_Catalog                     1038
#define IDC_Pigeonhole                  1039
#define IDC_EDFileSize                  1040
#define IDC_EDCreateTime                1041
#define IDC_EDModifyTime                1042
#define IDC_EDReadTime                  1043
#define IDC_FilePath                    1044
#define IDC_Show_FileName               1057
#define IDC_Show_FilePath               1058
#define IDC_COMBO2                      1059
#define IDC_COMBO3                      1060
#define IDC_COMBO4                      1061
#define IDC_COMBO5                      1061
#define IDC_STATIC_FSize                1063
#define IDC_STATIC_CTime                1064
#define IDC_STATIC_MTime                1065
#define IDC_STATIC_RTime                1066
#define IDC_STATIC_FilePath             1067
#define IDC_RADIO_ADD                   1067
#define IDC_RADIO_Modify                1068
#define IDC_RADIO_Del                   1069
#define ID_Button_DwDA                  1101
#define ID_Button_WDLB                  1102
#define ID_Button_Add                   1104
#define ID_Button_Modify                1105
#define ID_Button_Del                   1106
#define ID_Button_Scan                  1107
#define ID_Button_Attri                 1108
#define ID_Button_UserManage            1110
#define ID_Button_mimaModify            1111
#define ID_Button_LogManage             1112
#define ID_Button_BackUp                1114
#define ID_Button_Restore               1115
#define ID_Button_Exit                  1116
#define ID_MENUDWDAN                    32771
#define ID_MENUWDLB                     32772
#define ID_MENUADDWD                    32773
#define ID_MENUMODWD                    32774
#define ID_MENUDELWD                    32775
#define ID_MENULIULWD                   32776
#define ID_MENUYHGL                     32783
#define ID_MENUMODPWD                   32784
#define ID_MENURZGL                     32785
#define ID_EXIT                         32786
#define IDD_MENULookFileAttri           32787
#define IDD_DataBase_Save               32790
#define IDD_DataBase_Restore            32791
#define IDD_DataBase_BackUp             32800
#define IDD_MenuDB_BackUp               32800
#define ID_Menu_DBBackUp                32811
#define ID_Menu_DBRestore               32812
#define ID_MENUITEM32813                32813
#define ID_System_Exit                  32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
